### ISSUE TITLE
Expand the build matrix

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/libspatialindex-feedstock#2]
Same as https://github.com/conda-forge/geos-feedstock/issues/4

``` yaml
  matrix:
    - TARGET_ARCH: x86
    - TARGET_ARCH: x64
```
